from enum import StrEnum
from typing import Any

from pydantic import BaseModel, Field


class ErrorCode(StrEnum):
    AUTH_REQUIRED = "AUTH_REQUIRED"
    AUTH_INVALID = "AUTH_INVALID"
    PAIRING_REQUIRED = "PAIRING_REQUIRED"
    PAIRING_CODE_INVALID = "PAIRING_CODE_INVALID"
    PAIRING_CODE_EXPIRED = "PAIRING_CODE_EXPIRED"
    PROTOCOL_VERSION_MISMATCH = "PROTOCOL_VERSION_MISMATCH"
    SERVER_OFFLINE = "SERVER_OFFLINE"
    MODEL_NOT_CONFIGURED = "MODEL_NOT_CONFIGURED"
    MODEL_FILE_NOT_FOUND = "MODEL_FILE_NOT_FOUND"
    MODEL_LOAD_FAILED = "MODEL_LOAD_FAILED"
    MODEL_UNAVAILABLE = "MODEL_UNAVAILABLE"
    LLM_REQUEST_TIMEOUT = "LLM_REQUEST_TIMEOUT"
    LLM_STREAM_INTERRUPTED = "LLM_STREAM_INTERRUPTED"
    DATABASE_ERROR = "DATABASE_ERROR"
    CONFIG_VALIDATION_FAILED = "CONFIG_VALIDATION_FAILED"
    CONFIG_APPLY_FAILED = "CONFIG_APPLY_FAILED"
    SETTINGS_ROLLBACK_FAILED = "SETTINGS_ROLLBACK_FAILED"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    INTERNAL_ERROR = "INTERNAL_ERROR"


class ErrorDetail(BaseModel):
    code: ErrorCode
    message: str
    details: dict[str, Any] = Field(default_factory=dict)
    request_id: str | None = None
    retryable: bool = False


class ErrorEnvelope(BaseModel):
    error: ErrorDetail
